// alphabet 순서대로 정렬
object Versions {
    const val ACCOMPANIST_PAGER = "0.12.0"
    const val ANDROID_APP_COMPAT = "1.4.1"
    const val ANDROID_BUILD_TOOL = "7.2.0"
    const val ANDROID_CORE = "1.7.0"
    const val COIL = "1.4.0"
    const val COMPOSE = "1.2.0-rc02"
    const val COMPOSE_ACTIVITY = "1.4.0"
    const val COMPOSE_CONSTRAINT_LAYOUT = "1.1.0-alpha02"
    const val CONSTRAINT_LAYOUT = "2.1.3"
    const val COMPOSE_NAVIGATION = "2.4.2"
    const val FIREBASE_BOM = "29.1.0"
    const val FIREBASE_CRASHLYTICS = "2.9.0"
    const val GOOGLE_SERVICE = "4.3.10"
    const val HILT = "2.42"
    const val HILT_ANDROID = "1.0.0-beta01"
    const val JUNIT = "4.13.2"
    const val KAKAO_SDK = "2.10.0"
    const val KOTLIN = "1.6.10"
    const val KOTLIN_COROUTINES  = "1.5.1"
    const val MATERIAL_CALENDAR = "1.4.3"
    const val LIFECYCLE = "2.4.1"
    const val OKHTTP = "4.3.1"
    const val RETROFIT = "2.7.1"
    const val SECRETS_GRADLE = "2.0.1"
    const val TIMBER = "5.0.1"
    const val MOSHI = "1.13.0"
    const val INJECT = "1"
}
