// alphabet 순서대로 정렬
object Versions {
    const val ANDROID_APP_COMPAT = "1.4.1"
    const val ANDROID_BUILD_TOOL = "7.2.0"
    const val ANDROID_CORE = "1.7.0"
    const val COIL = "1.4.0"
    const val COMPOSE = "1.2.0-alpha08"
    const val COMPOSE_ACTIVITY = "1.4.0"
    const val CONSTRAINT_LAYOUT = "2.1.3"
    const val FIREBASE_BOM = "29.1.0"
    const val FIREBASE_CRASHLYTICS = "2.9.0"
    const val GOOGLE_SERVICE = "4.3.10"
    const val HILT = "2.42"
    const val HILT_ANDROID = "1.0.0-beta01"
    const val JUNIT = "4.13.2"
    const val KOTLIN = "1.6.20"
    const val KOTLIN_COROUTINES  = "1.5.1"
    const val LIFECYCLE = "2.4.1"
    const val OKHTTP = "4.3.1"
    const val RETROFIT = "2.7.1"
    const val TIMBER = "5.0.1"
}